scipion/pyworkflow/web/pages/urls.py
import os, sys
import pyworkflow as pw
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings
from pyworkflow.web.pages.settings import WS_ROOT, serviceFolders
from django.views.generic import TemplateView

#===============================================================================
# URL ASSOCIATION
#===============================================================================

mainUrls = ['',
    # To serve different static files
    (r'^resources/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^pages/doc/', include('django.contrib.admindocs.urls')),
    
    # If no path given, load the projects view
#     url(r'^$', 'app.views_project.projects'),
    url(r'^$', 'app.views_home.home'),
    url(r'^services/', 'app.views_project.webservice_projects'),
    
    #PROJECT (CONTENT, RUNTABLE AND GRAPH)
    url(r'^projects/', 'app.views_project.projects'),
    url(r'^create_project/$', 'app.views_project.create_project'),
    
    url(r'^check_project_id/$', 'app.views_project.check_project_id'),
    url(r'^delete_project/$', 'app.views_project.delete_project'),
    url(r'^project_content/$', 'app.views_project.project_content'),
    url(r'^get_protocols/$', 'app.views_project.get_protocols'),
    url(r'^search_protocol/$', 'app.views_project.search_protocol'),
    url(r'^tree_prot_view/$', 'app.views_project.tree_prot_view'),
    url(r'^run_table_graph/$', 'app.views_project.run_table_graph'),
    url(r'^protocol_info/$', 'app.views_project.protocol_info'),
    url(r'^update_graph_view/$', 'app.views_project.update_graph_view'),
    url(r'^update_prot_tree/$', 'app.views_project.update_prot_tree'),
    url(r'^save_selection/$', 'app.views_project.save_selection'),
    
    #GRAPH (RUN & DATA)
    url(r'^project_graph/$', 'app.views_graph.project_graph'),
    url(r'^object_graph/$', 'app.views_graph.object_graph'),
    url(r'^elements_graph/', 'app.views_graph.elements_graph'),
    
    #DATA (CONTENT)
    url(r'^data_content/$', 'app.views_data.data_content'),
    url(r'^object_info/$', 'app.views_data.object_info'),
    url(r'^object_tree/$', 'app.views_data.object_tree'),
    
    #UTILS
    url(r'^error/', 'app.views_util.error'), # Launch error page
    url(r'^render_column/', 'app.views_util.render_column'), # Load images dynamically
    url(r'^get_image_plot/', 'app.views_util.get_image_plot'), # Load plots images dynamically
    url(r'^get_image_path/', 'app.views_util.get_image_path'), # Load images dynamically
    url(r'^get_image/', 'app.views_util.get_image'), # Load images dynamically
    url(r'^get_slice/', 'app.views_util.get_slice'), # Load slices dynamically
    url(r'^browse_objects/$', 'app.views_util.browse_objects'), # Browse objects from the database
    url(r'^browse_relations/$', 'app.views_util.browse_relations'), # Browse relation objects from the database
    url(r'^browse_protocol_class/$', 'app.views_util.browse_protocol_class'), # Browse objects from the database
    url(r'^get_attributes/$', 'app.views_util.get_attributes'), # Get Label and Comment for an Object
    url(r'^set_attributes/$', 'app.views_util.set_attributes'), # Set Label and Comment for an Object
    url(r'^download_output/$', 'app.views_util.download_output'), # Download output files

    #PROTOCOL (INCLUDE FORM)
    url(r'^save_protocol/$', 'app.views_protocol.save_protocol'),
    url(r'^protocol/$', 'app.views_protocol.protocol'),
    url(r'^stop_protocol/$', 'app.views_protocol.stop_protocol'),
    url(r'^delete_protocol/$', 'app.views_protocol.delete_protocol'),
    url(r'^copy_protocol/$', 'app.views_protocol.copy_protocol'),
    url(r'^form/$', 'app.views_protocol.form'),

    #WIZARDS
    url(r'^wizard/$', 'app.em_wizard.wizard'),
    url(r'^get_image_mask/$', 'app.wizards.tools.get_image_mask'),
    url(r'^get_image_psd/$', 'app.wizards.tools.get_image_psd'),
    url(r'^get_image_bandpass/$', 'app.wizards.tools.get_image_bandpass'),
    url(r'^get_image_gaussian/$', 'app.wizards.tools.get_image_gaussian'),
    url(r'^get_image_filter_spider/$', 'app.wizards.spider_wizard.get_image_filter_spider'),
    url(r'^run_custom_mask_spider/$', 'app.wizards.spider_wizard.run_custom_mask_spider'),
    url(r'^get_resmap_plot/$', 'app.wizards.resmap_wizard.get_resmap_plot'),
    
    #VIEWERS
    url(r'^launch_viewer/$', 'app.em_viewer.launch_viewer'),
    url(r'^viewer_element/$', 'app.em_viewer.viewer_element'),
    url(r'^file_viewer/$', 'app.views_util.file_viewer'),
    url(r'^get_log/$', 'app.views_util.get_log'),
    
    #SHOWJ 
    url(r'^showj/$', 'app.views_showj.showj'), #Load showj web
    url(r'^update_session_table/$', 'app.views_showj.updateSessionTable'),
    url(r'^jsmol/$', 'app.views_showj.jsmol'),
    url(r'^get_chimera_html/$', 'app.views_showj.get_chimera_html'),
    
    #BROWSER & UPLOAD FILES
    url(r'^upload/', 'app.views_management.upload', name='upload'),
    url(r'^doUpload/', 'app.views_management.doUpload'),
    url(r'^upload_service/', 'app.views_management.upload_service'),
    url(r'^getPath/', 'app.views_management.getPath'),
    url(r'^getExtIcon/$', 'app.views_management.getExtIcon'),
    url(r'^get_file/$', 'app.views_util.get_file'),
    url(r'^get_image_dim/$', 'app.views_util.get_image_dim'),
    
    #TESTING
#    url(r'^testingSSH/', 'app.views_showj.testingSSH'), #Load web

    
    url(r'^home/', 'app.views_home.home'),
    url(r'^download_form/', 'app.views_home.download_form'),
    url(r'^doDownload/', 'app.views_home.doDownload'),

]

# Load URLS for webtools
from pyworkflow.utils.reflection import getModules
toolModules = getModules(WS_ROOT)

for tm in toolModules.values():
    mainUrls += tm.urls
    
 

# handler404 = "app.views_util.error"
# handler500 = "app.views_util.error"

urlpatterns = patterns(*mainUrls)

scipion/pyworkflow/web/app/forms.py
# **************************************************************************
# *
# * Authors:    Adrian Quintana (aquintana@cnb.csic.es)
# *                
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

from django import forms
from django.forms.forms import BoundField
from pyworkflow.object import List
import xmipp
from pyworkflow.utils.properties import Message
import pyworkflow.em.showj as sj

######################### Initialize Showj Form (Button toolbar) #####################        
class ShowjForm(forms.Form):
    #Init message properties file
    messagesForm = Message()
    
    # Init graphical components
    zoom = forms.CharField(required=True,
                            widget=forms.TextInput(attrs={'class' : 'menuInputNumber'}))
    
    goto = forms.IntegerField(required=True,
                              max_value=100,
                              min_value=1,
                              localize=False,
                              widget=forms.TextInput(attrs={'class' : 'menuInputNumber'}))
    
    
    cols = forms.IntegerField(label=messagesForm.LABEL_COLS,
                              required=False,
                              max_value=100,
                              min_value=1,
                              localize=False,
                              widget=forms.TextInput(attrs={'class' : 'menuInputNumber'}))

    rows = forms.IntegerField(label=messagesForm.LABEL_ROWS,
                              required=False,
                              max_value=100,
                              min_value=1,
                              localize=False,
                              widget=forms.TextInput(attrs={'class' : 'menuInputNumber'}))
    
    resliceComboBox = forms.ChoiceField(label=messagesForm.LABEL_RESLICE,
                                required=False,
                                choices=((xmipp.VIEW_Z_NEG, messagesForm.RESLICE_Z_NEGATIVE),
                                           (xmipp.VIEW_Y_NEG, messagesForm.RESLICE_Y_NEGATIVE),
                                           (xmipp.VIEW_X_NEG, messagesForm.RESLICE_X_NEGATIVE),
                                           (xmipp.VIEW_Y_POS, messagesForm.RESLICE_Y_POSITIVE),
                                           (xmipp.VIEW_X_POS, messagesForm.RESLICE_X_POSITIVE))
                                )

    # Init hidden fields
    path = forms.CharField(widget=forms.HiddenInput())
    allowRender = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    mode = forms.CharField(widget=forms.HiddenInput())
    colRowMode = forms.CharField(widget=forms.HiddenInput())
#    dims = forms.CharField(widget=forms.HiddenInput())
    
    imageMaxWidth = forms.CharField(widget=forms.HiddenInput())
    imageMinWidth = forms.CharField(widget=forms.HiddenInput())
    imageMaxHeight = forms.CharField(widget=forms.HiddenInput())
    imageMinHeight = forms.CharField(widget=forms.HiddenInput())
    
    mirrorY = forms.BooleanField(label=messagesForm.LABEL_MIRRORY, required=False)
#    applyTransformation = forms.BooleanField(label='Apply Transform', required=False)
    
#    CHOICES = (('transformMatrix', 'Apply Transform Matrix',), (IMG_ONLY_SHIFTS, 'Only Shifts',), ('wrap', 'Wrap',))
#    transformationChoice = forms.ChoiceField(widget=forms.RadioSelect, choices=(('transformMatrix', 'Apply Transform Matrix',), (IMG_ONLY_SHIFTS, 'Only Shifts',), ('wrap', 'Wrap',))
#                                             )
    applyTransformMatrix = forms.BooleanField(label=messagesForm.LABEL_APPLY_TRANSFORM, required=False)
    onlyShifts = forms.BooleanField(label=messagesForm.LABEL_ONLY_SHIFTS, required=False)
    wrap = forms.BooleanField(label=messagesForm.LABEL_WRAP, required=False)

    typeVolume = forms.CharField(widget=forms.HiddenInput())

    
    def __init__(self, dataset=None, tableLayoutConfiguration=None, labelsToRender = None, *args, **kwargs):
        #Init message properties file
        messagesForm = Message()
        
        super(ShowjForm, self).__init__(*args, **kwargs)
        
        if dataset is not None:
            self.fields['blockComboBox'] = forms.ChoiceField(label=messagesForm.LABEL_BLOCK_SELECTION,
                                                             required=False,
                                                             choices=tuple(zip(dataset.listTables(), dataset.listTables())))
            
            # This rendarable columns cannot have to access to the extra params
            namesToRender, labelsToRender = tableLayoutConfiguration.getRenderableColumns(extra=labelsToRender)
            
            if namesToRender:
                labelChoices = tuple(zip(namesToRender, labelsToRender))
                self.fields[sj.LABEL_SELECTED] = forms.ChoiceField(label=messagesForm.LABEL_LABEL_SELECTION,
                                                                required=False,
                                                                choices=labelChoices)
                if self.data[sj.MODE] != sj.MODE_GALLERY:
                    self.fields[sj.LABEL_SELECTED].widget = forms.HiddenInput()
            else:
                self.fields[sj.IMG_ZOOM].widget.attrs['readonly'] = True
                if self.data[sj.MODE] == sj.MODE_GALLERY:
                    self.fields[sj.GOTO].widget.attrs['readonly'] = True
                
            if dataset.getNumberSlices() > 1:
                labelColumn = dataset.getTable().getColumnValues(self.data[sj.LABEL_SELECTED])
                volumesToRenderComboBoxValues = tuple(zip(labelColumn, labelColumn))
                
                self.fields[sj.VOL_SELECTED] = forms.ChoiceField(label=messagesForm.LABEL_VOLUME_SELECTION,
                                                                required=False,
                                                                choices=volumesToRenderComboBoxValues)
                if self.data[sj.MODE] == sj.MODE_TABLE:
                    self.fields[sj.VOL_SELECTED].widget = forms.HiddenInput()
                if self.data[sj.MODE] != sj.MODE_GALLERY:                
                    self.fields[sj.VOL_VIEW].widget = forms.HiddenInput()
            else:
                self.fields[sj.VOL_VIEW].widget = forms.HiddenInput()
                
        else:
            self.fields[sj.IMG_ZOOM].widget = forms.HiddenInput()
            self.fields[sj.GOTO].widget = forms.HiddenInput()
            
            self.fields[sj.VOL_VIEW].widget = forms.HiddenInput()

            self.fields[sj.IMG_MIRRORY].widget = forms.HiddenInput()
            self.fields[sj.IMG_APPLY_TRANSFORM].widget = forms.HiddenInput()
            self.fields[sj.IMG_ONLY_SHIFTS].widget = forms.HiddenInput()
            self.fields[sj.IMG_WRAP].widget = forms.HiddenInput()
               
        
        if self.data[sj.MODE] != sj.MODE_GALLERY: 
            self.fields[sj.COLS].widget = forms.HiddenInput()
            self.fields[sj.ROWS].widget = forms.HiddenInput()
        
        if self.data[sj.MANUAL_ADJUST] == 'Off':
            self.fields[sj.COLS].widget.attrs['readonly'] = True
            self.fields[sj.ROWS].widget.attrs['readonly'] = True
            
        if self.data[sj.MODE] == 'column':    
            self.fields[sj.GOTO].widget.attrs['readonly'] = True
        
                                  
class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

scipion/pyworkflow/web/pages/templates/showj/showj_bottom_img_menu.html
 <script>
function getModeList(){return "image";}
 
$(document).ready(function(){
	var mode = document.forms['showjForm'].mode.value
	
	// Update the variable to know the old mode used
	$("input#oldModeShowj").val(mode)
	
	// Mark the selected items in the template
	var listSelectedItems = [{{listSelectedItems}}];
 	$("input#listSelectedItems").val(listSelectedItems)
	markSelectedItems(mode, listSelectedItems)
	
	// Update the enabled items in the template
	var listEnabledItems = [{{listEnabledItems}}];
 	$("input#listEnabledItems").val(listEnabledItems)
	updateEnabledItems(mode, listEnabledItems)
	
	// Update the ListChanges html variable
 	$("input#listChangesItems").val("");

 	
	/* ---- MODE TABLE UTILS ---------------*/
	//Update the enabled/selected items in the template between pagination
 	$("div.dataTables_paginate").click(function(){
 		initializeMultipleSelectionTool() //showj_table_utils.js
 		applyChangesToUpdate() //showj_menu_utils.js
 	});
 	
 	// Update the enabled/selected items in the template after change size of  
 	// the elements to show. 
 	$("div#data_table_length > label > select").change(function(){
 		initializeMultipleSelectionTool() //showj_table_utils.js
 		applyChangesToUpdate() //showj_menu_utils.js
 	});
 	
 	$('img.tableImages').dblclick(function(){
 		var src = $(this).attr("src") 
 		var imagePath = src.split("&image=")[1]
 		zoomImagePopUp(imagePath)
 	});
 	
 	//console.log("setImageSize used with zoom value")
	setImageSize(true);
});
</script>
	

<!-- 
<div id="asideMainContainer">
	<div id="createContainer" class="sectionMenu" style="float:right;">
		<a id="saveButton" href="javascript:createSubset()" class="btn buttonRed" style="padding: 5px 10px;">
			Create Subset
		</a>
	</div>

	<div class="sectionMenu">
		<img src="/resources/showj/separator.png" class="menuIcon">
	</div>

</div>	
 -->

scipion/pyworkflow/web/pages/templates/showj/showj_bottom_vol_menu.html
<script>
function getModeList(){return "volume";}

$(document).ready(function(){
	var mode = document.forms['showjForm'].mode.value
	
	// Update the variable to know the old mode used
	$("input#oldModeShowj").val(mode)
	
	var listSelectedItems = [{{listSelectedItems}}];
 	$("input#listSelectedItems").val(listSelectedItems)
 	//console.log("selectedItems: " + listSelectedItems)

	if (mode == "table"){
	 	markSelectedItems(mode, listSelectedItems)
	} else if (mode == "gallery"){
// 		var index = $("select#id_volumesToRenderComboBox option:selected=selected").index()
// 		var index = document.getElementById("select#id_volumesToRenderComboBox").selectedIndex
// 		$("input#listSelectedItems").val(index+1)
		
// 		console.log("index: " + index)
	}
 	
 	$("select#id_volumesToRenderComboBox").change(function(){
 		new Messi("<i class='fa fa-picture-o'/>  Loading Volume...",{
			modal : true
		});
 	});
 	
 	$("select#id_resliceComboBox").change(function(){
 		new Messi("<i class='fa fa-picture-o'/>  Loading Volume...",{
			modal : true
		});
 	});
 	
 	//console.log("setImageSize used with zoom value")
	setImageSize(true);
 	
});
</script>
	

scipion/pyworkflow/web/pages/templates/showj/showj_column.html
{% extends 'showj/showj_base.html' %} 
{% block head %}
<!-- CSS -->
<link type="text/css" href="/static/css/jquery-ui_smoothness.css" rel="stylesheet" /> 
<link type="text/css" href="/static/css/demo_table_jui.css" rel="stylesheet" />

<!-- TABLE STYLES 
Overwrite general section property for table view -->
<style type="text/css">
section {
	display:block;
}
#displayTableContainer{
	width:60%;
	text-align:center;
	margin-bottom:10px;
	display:block;
}
</style>

<!-- JS -->

<script type="text/javascript" src="{{jquery_datatable}}"></script>

<!-- Datatable extra api -->
<script type="text/javascript">
$.fn.dataTableExt.oApi.fnVisibleToColumnIndex = function ( oSettings, iMatch )
{
    return oSettings.oApi._fnVisibleToColumnIndex( oSettings, iMatch );
};
$.fn.dataTableExt.oApi.fnColumnIndexToVisible = function ( oSettings, iMatch )
{
  return oSettings.oApi._fnColumnIndexToVisible( oSettings, iMatch );
};
$.fn.dataTableExt.oApi.fnGetColumnIndex = function ( oSettings, sCol )
{
    var cols = oSettings.aoColumns;
    for ( var x=0, xLen=cols.length ; x<xLen ; x++ )
    {
        if ( cols[x].sTitle.toLowerCase() == sCol.toLowerCase() )
        {
            return x;
        };
    }
    return -1;
};

</script>

<script type="text/javascript" src="{{jquerydataTables_colreorder}}"></script>
<script type="text/javascript" src="{{jquerydataTables_colreorder_resize}}"></script>
<script type="text/javascript" src="{{jeditable}}"></script>
<script type="text/javascript" src="{{transpose_lib}}"></script>
<script type="text/javascript" src="{{showj_alt_js}}"></script>

<script type="text/javascript">
/* Initialize datatable table */
var oTable;
/* Initialize Table Layout Configuration from json variable*/
var jsonTableLayoutConfiguration = {{tableLayoutConfiguration|safe }}
/* console.log("json",jsonTableLayoutConfiguration) */
/*  Initialize variable to keep changes*/
var changes={}

$(document).ready(function() {
	
	initializeSelectionRowEvent() 
	initializeGoToEvent()
	initializeTableWidth()
	
	/* Init the table */
	oTable = $('#data_table').dataTable(
				{
			        "bPaginate": true,
			        "bLengthChange": true,
			        "bFilter": true,
			        "bSort": true,
			        "bInfo": true,
			        "bAutoWidth": true,
			        "sDom": '<"#displayTableContainer">ZRrt',
			        /* "sDom": 'Rrt', */
			        /* "sDom": 'T<"clear">lfrtip', */
 			        "oColReorder": {
		    			"aiOrder": jsonTableLayoutConfiguration.colsOrder
		    		},  
		    		
		    		"bProcessing": true,
/* 		            "bServerSide": true, */
/* 		            "sAjaxSource": "/get_table/", */
		            
		            "fnServerParams": function ( aoData ) {
		                aoData.push( {
		                	"path": "{{inputParameters.path}}",
		                	"block": "{{inputParameters.block}}",
		                	"allowRender": "{{inputParameters.allowRender}}",
		                	"imageDim": "{{inputParameters.imageDim}}"
		                		} );
		            },
		            "fnDrawCallback": function( oSettings ) {
		            	if ( typeof oTable != 'undefined' ) {
		            		setElementsEditable(null)
		            	}
		              },
		             
		            "bDeferRender": true,
		    		/* "bRetrieve": true */
		    		"aaData": generateDataForTable(),	
		    		"aoColumnDefs": getColumnsDefinition(), 
		            "bJQueryUI": true,
		    		"sPaginationType": "full_numbers"
			    }		
			);
	
	$("#displayTableContainer").html("<a href='#' onclick='showTableConfig()'>{{msg.LABEL_DISPLAY_TABLE_CONFIG}}</a>")
	
	initializeMultipleSelectionTool()
	initializeColumnHeader()
	
	/*  Transpose data table after all events have been initialized*/
	oTable.fnTranspose(true)

	setElementsEditable(null)
	
	
} );

/* Generate data for datatable from table dataset model */
function generateDataForTable(){
	dataForTable = new Array();
	{% for row in tableDataset.getRows %}
		dataRowForTable = new Array()
		var row_id
		{% for cell in row %}
			dataRowForTable.push("{{cell}}")
			{% if forloop.first	%}
				row_id = "{{cell}}"
			{% endif %}

		{% endfor %}
		/* dataRowForTable.push("DT_RowId\": \""+row_id+"\"") */
		/* dataRowForTable.push("DT_RowId: "+row_id) */
		dataForTable.push(dataRowForTable)
	{% endfor %}
	return dataForTable;
}
</script>
{% endblock %}

{% block content_menu %}{% endblock %}
			
{% block content_view %}
<div id="configurationContainer">
	<div id="tableConfigurationContainer">
		<table id="firstTableConfiguration">
			<tr>
				<td>{{msg.LABEL_LABEL}}</td>
				<td>{{msg.LABEL_VISIBLE}}</td>
				<td>{{msg.LABEL_RENDER}}</td>
				<td>{{msg.LABEL_EDIT}}</td>
			</tr>
			{% for column in tableDataset.getColumns %}
				{% if tableDataset.getNumberOfColumns < 6 or forloop.counter0|divisibleby:2 %}
			 		 <tr>
			 		 	<td>{{column.getName}}</td>
			 		 	<td><input type="checkbox" id="{{column.getName}}_visible"></td>
			 		 	<td><input type="checkbox" id="{{column.getName}}_renderable"></td>
			 		 	<td><input type="checkbox" id="{{column.getName}}_editable"></td>
			 		 </tr>
	 			{% endif %} 
			{% endfor %}
		</table>
		
		{% if tableDataset.getNumberOfColumns > 5 %}
		<table id="secondTableConfiguration">
			<tr>
				<td>{{msg.LABEL_LABEL}}</td>
				<td>{{msg.LABEL_VISIBLE}}</td>
				<td>{{msg.LABEL_RENDER}}</td>
				<td>{{msg.LABEL_EDIT}}</td>
			</tr>
			{% for column in tableDataset.getColumns %}
				 {% if forloop.counter0|divisibleby:2 == False %}
			 		 <tr>
			 		 	<td>{{column.getName}}</td>
			 		 	<td><input type="checkbox" id="{{column.getName}}_visible"></td>
			 		 	<td><input type="checkbox" id="{{column.getName}}_renderable"></td>
			 		 	<td><input type="checkbox" id="{{column.getName}}_editable"></td>
			 		 </tr>
	 			{% endif %} 
			{% endfor %}
		</table>
		{% endif %} 
	</div>
	<div id="tableConfigurationButtonBar">
		<a href="javascript:saveTableConfiguration();" class="btn buttonGrey">{{msg.LABEL_BUTTON_OK}}</a>
		<a href="javascript:$('#configurationContainer').slideUp('slow');" class="btn buttonGrey">{{msg.LABEL_BUTTON_CANCEL}}</a>
	</div>
</div>

	
<div id="table_container" style="overflow-x:auto">
		<table cellspacing="0" id="data_table" width="60%">
		</table>
</div>
			
{% endblock %}

scipion/pyworkflow/web/pages/templates/showj/showj_gallery.html
{% extends 'showj/showj_base.html' %} 
		
{% block head %}
<!-- JS -->
<script src="{{showj_alt_js}}" type="text/javascript"></script>

<script type="text/javascript">
var hoverElement;
$(document).ready(function(){
	initRenderFunction("{{form.labelsToRenderComboBox.value}}");
	initializeImageLoad()
	initializeImageEvents({% if dataset.getTable.hasEnabledColumn == True %}true{% else %} false {% endif %})
	initializeWindowLoadEvents()
	initializeGoToEvents()
});
</script>
{% endblock %}

{% block content_menu %}
{% endblock %}

{% block content_view %}	

	{% if dataset.getNumberSlices == 1 %}
	    
		{% for id,enable,data,transformationMatrix in tableDataset.getDataToRenderAndExtra %}
			<div class="img_container" id="img_container___{{id}}">
				<div class="img_inner_container">
					<img class="tableImages" title="{{data}}" data-real_src="{{abs_url}}/render_column/?renderFunc=get_image&image={{data}}"/>
						{% if tableDataset.hasEnabledColumn %}
						<img class="enabledGallery
						{% if enable == 0 %}
						selected
						{% endif %}
						" src="{{abs_url}}/resources/showj/enabled_gallery.png" id="enabled___{{id}}" onclick="enableDisableImage(this);" 
						{% if enable == 0 %} 
						style="display:block;"
						{% endif %}	
						/>
					{% endif %} 
				</div>
				<div id="column_label">{{id}}</div> 
			</div>
		{% endfor %}
		
	{% else %}	
		
		{% for i in dataset.getNumberSlicesForTemplate %}
			<div class="img_container" id="img_container___{{i}}">
				<div class="img_inner_container">
					<img class="tableImages" 
					title="Slice {{i|add:1}} from {{dataset.getVolumeName}}" 
					data-real_src="{{abs_url}}/render_column/?renderFunc=get_slice&image={{i|add:1}}__slice__{{dataset.getVolumeName}}"/>
				</div>
				<div id="column_label">{{i|add:1}}</div> 
			</div>
		{% endfor %}
	
	{% endif %}	 

{% endblock %}
{% block content_end_page %}	{% endblock %}

{% block bottom_menu %}
	{% if dataset.getNumberSlices > 1 or form.typeVolume.value == 'pdb'%} 
		<!-- VOLUME MENU -->
		{% include "showj/showj_bottom_vol_menu.html" %}
	{% else %}
		<!-- IMAGE MENU -->
		{% include "showj/showj_bottom_img_menu.html" %}
	{% endif %}
{% endblock %}